version: "3.9"
services:
  backend:
    build:
      context: ./backend
    image: kv-backend:latest
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: kv-frontend:latest
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped
